services:
  core:
    container_name: core
    image: core
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
    build:
      context: .
    ports:
      - '${PORT}:${PORT}'
    networks:
      - core-network
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:13.18
    ports:
      - '5678:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - core-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    mem_limit: 1g
    cpus: 0.5
    restart: unless-stopped

networks:
  core-network: {}

volumes:
  postgres_data: {}
